apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: arca-spark-postgres
    access: proxy
    url: postgres:5432
    user: arca_admin
    secureJsonData:
      password: arca_secret_2026
    jsonData:
      database: arca_spark_db
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
    isDefault: true

  - name: Loki
    type: loki
    uid: arca-spark-loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    jsonData:
      maxLines: 1500
